# Generated by Django 6.0.4 on 2026-05-02 03:05

import django.core.validators
import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomicIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("unit", models.CharField(blank=True, max_length=50)),
                ("timestamp", models.DateTimeField(db_index=True)),
            ],
            options={
                "ordering": ["timestamp", "name"],
            },
        ),
        migrations.CreateModel(
            name="PolicyDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("source", models.URLField(blank=True)),
                ("published_date", models.DateTimeField(db_index=True)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="SentimentResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("Hawkish", "Hawkish"),
                            ("Dovish", "Dovish"),
                            ("Neutral", "Neutral"),
                        ],
                        max_length=20,
                    ),
                ),
                ("primary_impact", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment",
                        to="macro_sentiment.policydocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-document__published_date"],
            },
        ),
    ]
