# Generated by Django 6.0.4 on 2026-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("macro_sentiment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policydocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("RBI_MONETARY_POLICY", "RBI monetary policy"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="fetched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="policydocument",
            name="is_latest",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
